In [63]:
import pandas as pd
mups = pd.read_csv('/Users/quintonaguilera/Desktop/Aederide & Toledo/capsule_research/data/Data.xlsx - MUPS.csv', 
                 delimiter=",")

mups = mups[mups['Tablet']=='MUPS']

independent_variables = ['Excipient', 'Tablet', 'CP', 'Family', 'AoR',
       'Span', 'MPS', 'BD', 'HR', 'Y', 'E']

mups = mups[independent_variables]

mups_40 = mups[mups['CP'] == 40]

In [75]:
mups.corr()

,CP,AoR,Span,MPS,BD,HR,Y,E
CP,1.000000,-0.088756,-0.039236,0.074681,0.145941,-0.144571,-0.031335,0.915946
AoR,-0.088756,1.000000,0.264815,-0.949165,-0.597561,0.815577,0.464014,-0.040012
Span,-0.039236,0.264815,1.000000,0.046660,-0.011341,0.268293,0.743000,-0.014760
MPS,0.074681,-0.949165,0.046660,1.000000,0.585916,-0.740844,-0.227840,0.035973
BD,0.145941,-0.597561,-0.011341,0.585916,1.000000,-0.921788,0.023534,0.078943
HR,-0.144571,0.815577,0.268293,-0.740844,-0.921788,1.000000,0.256254,-0.079833
Y,-0.031335,0.464014,0.743000,-0.227840,0.023534,0.256254,1.000000,0.004791
E,0.915946,-0.040012,-0.014760,0.035973,0.078943,-0.079833,0.004791,1.000000

<h1>Need to drop collinear vars</h1>

In [65]:
def cat_var_to_onehot_encoded(df, col):
    series = df[col]
    one_hot = pd.get_dummies(series)
    df = pd.concat([df, one_hot], axis=1)
    df = df.drop(col, axis = 1)
    return df

In [66]:
mups_40 = cat_var_to_onehot_encoded(mups_40, 'Excipient')
# mups_40 = cat_var_to_onehot_encoded(mups_40, 'Family')

In [73]:
dep = mups_40['E']
# indep = mups_40.drop(['E', 'Y', 'Span', 'BD', 'HR', 'AoR', 'Tablet', 'CP'], axis = 1)
indep = mups_40.drop(['E', 'Y', 'Span', 'BD', 'HR', 'AoR', 'Tablet', 'CP', 'Family', 'MPS'], axis = 1)

In [74]:
indep

     KG-1000  KG-802  PH-101  PH-102  UF-702  UF-711
4          0       0       1       0       0       0
5          0       0       1       0       0       0
6          0       0       1       0       0       0
7          0       0       1       0       0       0
24         0       0       1       0       0       0
25         0       0       1       0       0       0
26         0       0       1       0       0       0
27         0       0       1       0       0       0
40         0       0       0       1       0       0
41         0       0       0       1       0       0
42         0       0       0       1       0       0
43         0       0       0       1       0       0
58         0       0       0       1       0       0
59         0       0       0       1       0       0
60         0       0       0       1       0       0
61         0       0       0       1       0       0
74         0       0       0       0       1       0
75         0       0       0       0       1       0
76         0       0       0       0       1       0
77         0       0       0       0       1       0
94         0       0       0       0       1       0
95         0       0       0       0       1       0
96         0       0       0       0       1       0
97         0       0       0       0       1       0
110        0       0       0       0       0       1
111        0       0       0       0       0       1
112        0       0       0       0       0       1
113        0       0       0       0       0       1
126        0       0       0       0       0       1
127        0       0       0       0       0       1
128        0       0       0       0       0       1
129        0       0       0       0       0       1
142        0       1       0       0       0       0
143        0       1       0       0       0       0
144        0       1       0       0       0       0
145        0       1       0       0       0       0
158        0       1       0       0       0       0
159        0       1       0       0       0       0
160        0       1       0       0       0       0
161        0       1       0       0       0       0
174        1       0       0       0       0       0
175        1       0       0       0       0       0
176        1       0       0       0       0       0
177        1       0       0       0       0       0
188        1       0       0       0       0       0
189        1       0       0       0       0       0
190        1       0       0       0       0       0
191        1       0       0       0       0       0